export const SET_ERROR = 'SET_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_USER_WITH_EMAIL_SUCCESS = 'LOGIN_USER_WITH_EMAIL_SUCCESS';
export const LOGIN_USER_WITH_EMAIL_FAIL = 'LOGIN_USER_WITH_EMAIL_FAIL';
export const REGISTER_USER_WITH_EMAIL_SUCCESS = 'REGISTER_USER_WITH_EMAIL_SUCCESS';
export const REGISTER_USER_WITH_EMAIL_FAIL = 'REGISTER_USER_WITH_EMAIL_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_PROFILE = 'GET_PROFILE';
